transfer_url_base = "https://mango-services.github.io/src/re-directed/{namespace}/{type}"

# html
html_base = "<meta http-equiv=\"refresh\" content=\"0;url={url}\">"

# markdown
markdown_base = """# Link List

| Namespace |   Path    | Original URL | Transfer URL |
|-----------|-----------|--------------|--------------|
"""
table_base = "| `{namespace}` | `{path}` | `{original_url}` | {transfer_url} |"

[url_mapping]
# source code
github = "https://www.github.com"
# minecraft mod publish
curseforge = "https://www.curseforge.com"
modrinth = "https://www.modrinth.com/"
mcmod = "https://www.mcmod.cn/"
# social media
youtube = "https://www.youtube.com/"
reddit = "https://www.reddit.com/"
twitch = "https://www.twitch.tv/"
odysee = "https://www.odysee.com/"
facebook = "https://www.facebook.com/"
twitter = "https://www.twitter.com/"
