transfer_url_base = "https://mango-serives.github.io/src/link-list/{domain}/{filename}"
url_base = "<meta http-equiv=\"refresh\" content=\"0;url={url}\">"
markdown_base = """<link href="http://github.com/yrgoldteeth/darkdowncss/raw/master/darkdown.css" rel="stylesheet"></link>
# Link List

| Domain | namespace | raw_url | transfer_url |
|--------|-----------|---------|--------------|
"""
table_base = "| `{domain}` | `{namespace}` | [{raw_url}]({raw_url}) | [{transfer_url}]({transfer_url}) |\n"

[RawOresProcessing-Datapack]
"www.curseforge.com" = "/minecraft/texture-packs/raw-ores-processing-datapack"
"www.mcmod.cn"       = "/class/7643"
"www.github.com"     = "/Mango-Minecraft-Project/RawOresProcessing-Datapack"

[WoolRecipes-Datapack]
"www.curseforge.com" = "/minecraft/texture-packs/wool-recipes-datapack"
"www.mcmod.cn"       = "/class/7623"
"www.github.com"     = "/Mango-Minecraft-Project/WoolRecipes-Datapack"

